---
server:
  port: 9199
  servlet:
    context-path: /pets
message: Hello from github
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size:  2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
